import { FlashcardData } from './types';

export const STATIC_DECK_MOVER_MUDAR_POR: FlashcardData[] = [
  // CATEGORIA 1 - VERBS
  {
    id: 'static_1',
    word: 'to move',
    translation: 'mover, mudar',
    pronunciation: '/tu muv/',
    portuguesePhonetic: 'tu múv',
    syllables: ['to', 'move'],
    exampleSentence: 'I need to move this table.',
    exampleTranslation: 'Eu preciso mover esta mesa.',
    grammarExplanation: 'Verbo regular. Pode significar mover algo de lugar ou mudar de residência.'
  },
  {
    id: 'static_2',
    word: 'to put',
    translation: 'colocar, pôr',
    pronunciation: '/tu pʊt/',
    portuguesePhonetic: 'tu pût',
    syllables: ['to', 'put'],
    exampleSentence: 'Put the book on the desk.',
    exampleTranslation: 'Coloque o livro na escrivaninha.',
    grammarExplanation: 'Verbo irregular (put - put - put). Muito usado com preposições (phrasal verbs).'
  },
  
  // CATEGORIA 2 - NEW WORDS
  {
    id: 'static_3',
    word: 'armchair',
    translation: 'poltrona',
    pronunciation: '/ˈɑrmˌtʃɛr/',
    portuguesePhonetic: 'árm-tcher',
    syllables: ['arm', 'chair'],
    exampleSentence: 'He is sitting in the armchair.',
    exampleTranslation: 'Ele está sentado na poltrona.',
  },
  {
    id: 'static_4',
    word: 'chair',
    translation: 'cadeira',
    pronunciation: '/tʃɛr/',
    portuguesePhonetic: 'tcher',
    syllables: ['chair'],
    exampleSentence: 'This chair is very comfortable.',
    exampleTranslation: 'Esta cadeira é muito confortável.',
  },
  {
    id: 'static_5',
    word: 'desk',
    translation: 'escrivaninha',
    pronunciation: '/dɛsk/',
    portuguesePhonetic: 'dést',
    syllables: ['desk'],
    exampleSentence: 'My computer is on the desk.',
    exampleTranslation: 'Meu computador está na escrivaninha.',
  },
  {
    id: 'static_6',
    word: 'carpet',
    translation: 'tapete',
    pronunciation: '/ˈkɑrpɪt/',
    portuguesePhonetic: 'cár-pet',
    syllables: ['car', 'pet'],
    exampleSentence: 'The dog is sleeping on the carpet.',
    exampleTranslation: 'O cachorro está dormindo no tapete.',
  },
  {
    id: 'static_7',
    word: 'tidy',
    translation: 'arrumado(a)',
    pronunciation: '/ˈtaɪdi/',
    portuguesePhonetic: 'tái-di',
    syllables: ['ti', 'dy'],
    exampleSentence: 'Her room is always tidy.',
    exampleTranslation: 'O quarto dela está sempre arrumado.',
  },
  {
    id: 'static_8',
    word: 'broken',
    translation: 'quebrado(a)',
    pronunciation: '/ˈbroʊkən/',
    portuguesePhonetic: 'brôu-ken',
    syllables: ['bro', 'ken'],
    exampleSentence: 'The window is broken.',
    exampleTranslation: 'A janela está quebrada.',
  },
  {
    id: 'static_9',
    word: 'messy',
    translation: 'bagunçado(a)',
    pronunciation: '/ˈmɛsi/',
    portuguesePhonetic: 'mé-si',
    syllables: ['mes', 'sy'],
    exampleSentence: 'His desk is very messy.',
    exampleTranslation: 'A escrivaninha dele é muito bagunçada.',
  },
  {
    id: 'static_10',
    word: 'dirty',
    translation: 'sujo(a)',
    pronunciation: '/ˈdɜrti/',
    portuguesePhonetic: 'dâr-ti',
    syllables: ['dir', 'ty'],
    exampleSentence: 'These shoes are dirty.',
    exampleTranslation: 'Estes sapatos estão sujos.',
  },
  {
    id: 'static_11',
    word: 'to the right',
    translation: 'para a direita',
    pronunciation: '/tu ðə raɪt/',
    portuguesePhonetic: 'tu dâ ráit',
    syllables: ['to', 'the', 'right'],
    exampleSentence: 'Move the chair to the right.',
    exampleTranslation: 'Mova a cadeira para a direita.',
  },
  {
    id: 'static_12',
    word: 'to the left',
    translation: 'para a esquerda',
    pronunciation: '/tu ðə lɛft/',
    portuguesePhonetic: 'tu dâ léft',
    syllables: ['to', 'the', 'left'],
    exampleSentence: 'Put the lamp to the left.',
    exampleTranslation: 'Coloque a luminária para a esquerda.',
  },
  {
    id: 'static_13',
    word: 'next to',
    translation: 'ao lado de',
    pronunciation: '/nɛkst tu/',
    portuguesePhonetic: 'nékst tu',
    syllables: ['next', 'to'],
    exampleSentence: 'The table is next to the sofa.',
    exampleTranslation: 'A mesa está ao lado do sofá.',
  },
  {
    id: 'static_14',
    word: 'closet',
    translation: 'guarda-roupa, armário',
    pronunciation: '/ˈklɑzɪt/',
    portuguesePhonetic: 'cló-zet',
    syllables: ['clos', 'et'],
    exampleSentence: 'Hang your coat in the closet.',
    exampleTranslation: 'Pendure seu casaco no guarda-roupa.',
  },
  
  // CATEGORIA 3 - USEFUL PHRASES
  {
    id: 'static_15',
    word: 'Put away these clothes in the closet, please.',
    translation: 'Guarde estas roupas no guarda-roupa, por favor.',
    pronunciation: '/pʊt əˈweɪ ðiz kloʊðz ɪn ðə ˈklɑzɪt, pliz/',
    portuguesePhonetic: 'pût a-uêi díz clôudz in dâ cló-zet, plíz',
    syllables: ['Put', 'a-way', 'these', 'clothes', 'in', 'the', 'clos-et', 'please'],
    exampleSentence: 'Put away these clothes in the closet, please.',
    exampleTranslation: 'Guarde estas roupas no guarda-roupa, por favor.',
  },
  {
    id: 'static_16',
    word: "Don't put this chair here. It's broken.",
    translation: 'Não coloque essa cadeira aqui. Está quebrada.',
    pronunciation: '/doʊnt pʊt ðɪs tʃɛr hɪr. ɪts ˈbroʊkən/',
    portuguesePhonetic: 'dôunt pût dis tcher rír. its brôu-ken',
    syllables: ["Don't", 'put', 'this', 'chair', 'here.', "It's", 'bro-ken'],
    exampleSentence: "Don't put this chair here. It's broken.",
    exampleTranslation: 'Não coloque essa cadeira aqui. Está quebrada.',
  },
  {
    id: 'static_17',
    word: 'What a mess!',
    translation: 'Que bagunça!',
    pronunciation: '/wʌt ə mɛs/',
    portuguesePhonetic: 'uát a més',
    syllables: ['What', 'a', 'mess'],
    exampleSentence: 'What a mess! Clean your room.',
    exampleTranslation: 'Que bagunça! Limpe seu quarto.',
  },
  {
    id: 'static_18',
    word: 'Move the desk to the right.',
    translation: 'Mova a escrivaninha para a direita.',
    pronunciation: '/muv ðə dɛsk tu ðə raɪt/',
    portuguesePhonetic: 'múv dâ dést tu dâ ráit',
    syllables: ['Move', 'the', 'desk', 'to', 'the', 'right'],
    exampleSentence: 'Move the desk to the right.',
    exampleTranslation: 'Mova a escrivaninha para a direita.',
  },
  {
    id: 'static_19',
    word: 'Put the carpet next to the bed.',
    translation: 'Coloque o tapete ao lado da cama.',
    pronunciation: '/pʊt ðə ˈkɑrpɪt nɛkst tu ðə bɛd/',
    portuguesePhonetic: 'pût dâ cár-pet nékst tu dâ béd',
    syllables: ['Put', 'the', 'car-pet', 'next', 'to', 'the', 'bed'],
    exampleSentence: 'Put the carpet next to the bed.',
    exampleTranslation: 'Coloque o tapete ao lado da cama.',
  },
  {
    id: 'static_20',
    word: 'My room is very tidy today.',
    translation: 'Meu quarto está muito arrumado hoje.',
    pronunciation: '/maɪ rum ɪz ˈvɛri ˈtaɪdi təˈdeɪ/',
    portuguesePhonetic: 'mái rum iz vé-ri tái-di tu-dêi',
    syllables: ['My', 'room', 'is', 'ver-y', 'ti-dy', 'to-day'],
    exampleSentence: 'My room is very tidy today.',
    exampleTranslation: 'Meu quarto está muito arrumado hoje.',
  },
  {
    id: 'static_21',
    word: 'Can you move this armchair?',
    translation: 'Você pode mover esta poltrona?',
    pronunciation: '/kæn ju muv ðɪs ˈɑrmˌtʃɛr/',
    portuguesePhonetic: 'kén iu múv dis árm-tcher',
    syllables: ['Can', 'you', 'move', 'this', 'arm-chair'],
    exampleSentence: 'Can you move this armchair?',
    exampleTranslation: 'Você pode mover esta poltrona?',
  },
  {
    id: 'static_22',
    word: 'The kitchen is dirty.',
    translation: 'A cozinha está suja.',
    pronunciation: '/ðə ˈkɪtʃən ɪz ˈdɜrti/',
    portuguesePhonetic: 'dâ kí-tchen iz dâr-ti',
    syllables: ['The', 'kitch-en', 'is', 'dir-ty'],
    exampleSentence: 'The kitchen is dirty.',
    exampleTranslation: 'A cozinha está suja.',
  },
  {
    id: 'static_23',
    word: 'Put it on the table.',
    translation: 'Coloque isso na mesa.',
    pronunciation: '/pʊt ɪt ɑn ðə ˈteɪbəl/',
    portuguesePhonetic: 'pût it on dâ têi-bâl',
    syllables: ['Put', 'it', 'on', 'the', 'ta-ble'],
    exampleSentence: 'Put it on the table.',
    exampleTranslation: 'Coloque isso na mesa.',
  },
  {
    id: 'static_24',
    word: 'Move away from the door.',
    translation: 'Afaste-se da porta.',
    pronunciation: '/muv əˈweɪ frʌm ðə dɔr/',
    portuguesePhonetic: 'múv a-uêi fram dâ dór',
    syllables: ['Move', 'a-way', 'from', 'the', 'door'],
    exampleSentence: 'Move away from the door.',
    exampleTranslation: 'Afaste-se da porta.',
  },
  {
    id: 'static_25',
    word: 'Put your shoes away.',
    translation: 'Guarde seus sapatos.',
    pronunciation: '/pʊt jʊr ʃuz əˈweɪ/',
    portuguesePhonetic: 'pût iór chúz a-uêi',
    syllables: ['Put', 'your', 'shoes', 'a-way'],
    exampleSentence: 'Put your shoes away.',
    exampleTranslation: 'Guarde seus sapatos.',
  },
  {
    id: 'static_26',
    word: 'She moved to a new house.',
    translation: 'Ela se mudou para uma casa nova.',
    pronunciation: '/ʃi muvd tu ə nu haʊs/',
    portuguesePhonetic: 'chí múvd tu a niú ráus',
    syllables: ['She', 'moved', 'to', 'a', 'new', 'house'],
    exampleSentence: 'She moved to a new house.',
    exampleTranslation: 'Ela se mudou para uma casa nova.',
  },
  {
    id: 'static_27',
    word: 'Where did you put my keys?',
    translation: 'Onde você colocou minhas chaves?',
    pronunciation: '/wɛr dɪd ju pʊt maɪ kiz/',
    portuguesePhonetic: 'uér did iu pût mái kíz',
    syllables: ['Where', 'did', 'you', 'put', 'my', 'keys'],
    exampleSentence: 'Where did you put my keys?',
    exampleTranslation: 'Onde você colocou minhas chaves?',
  },
  {
    id: 'static_28',
    word: 'The TV is broken.',
    translation: 'A TV está quebrada.',
    pronunciation: '/ðə ˌtiˈvi ɪz ˈbroʊkən/',
    portuguesePhonetic: 'dâ ti-ví iz brôu-ken',
    syllables: ['The', 'TV', 'is', 'bro-ken'],
    exampleSentence: 'The TV is broken.',
    exampleTranslation: 'A TV está quebrada.',
  },
  {
    id: 'static_29',
    word: 'Please, tidy up your room.',
    translation: 'Por favor, arrume seu quarto.',
    pronunciation: '/pliz, ˈtaɪdi ʌp jʊr rum/',
    portuguesePhonetic: 'plíz, tái-di ap iór rum',
    syllables: ['Please', 'ti-dy', 'up', 'your', 'room'],
    exampleSentence: 'Please, tidy up your room.',
    exampleTranslation: 'Por favor, arrume seu quarto.',
  },
  {
    id: 'static_30',
    word: 'Put the box to the left.',
    translation: 'Coloque a caixa para a esquerda.',
    pronunciation: '/pʊt ðə bɑks tu ðə lɛft/',
    portuguesePhonetic: 'pût dâ bóks tu dâ léft',
    syllables: ['Put', 'the', 'box', 'to', 'the', 'left'],
    exampleSentence: 'Put the box to the left.',
    exampleTranslation: 'Coloque a caixa para a esquerda.',
  }
];
