export type SupportedLanguage = "en" | "es";

export interface FlashcardData {
  id: string;
  word: string;
  translation: string;
  pronunciation: string;
  portuguesePhonetic: string;
  syllables: string[];
  exampleSentence: string;
  exampleTranslation: string;
  grammarExplanation?: string;
}

export enum AppState {
  HOME = "HOME",
  LOADING = "LOADING",
  STUDY = "STUDY",
  SUMMARY = "SUMMARY",
  ERROR = "ERROR",
}

export interface StudySession {
  topicId: string;
  topicLabel: string;
  language: SupportedLanguage;
  cards: FlashcardData[];
  currentIndex: number;
}

export const PREDEFINED_TOPICS = [
  {
    id: 'leccion_1_gramatica_c1_s',
    label: 'Lección 1',
    isStatic: true,
    group: 'Gramática C1',
    description: 'Presente Simple vs Continuo'
  },
  {
    id: 'leccion_3_gramatica_c1_s',
    label: 'Lección 3',
    isStatic: true,
    group: 'Gramática C1',
    description: 'Hábitos y Suposiciones (Will, Would, Should)'
  },
  {
    id: 'leccion_2_gramatica_c1_s',
    label: 'Lección 2',
    isStatic: true,
    group: 'Gramática C1',
    description: 'Pasado Continuo, Perfecto y Pluscuamperfecto'
  },
  {
    id: 'lesson_1_grammar_c1',
    label: 'Lesson 1',
    isStatic: true,
    group: 'Grammar C1',
    description: 'Present Simple vs Present Continuous'
  },
  {
    id: 'lesson_2_grammar_c1',
    label: 'Lesson 2',
    isStatic: true,
    group: 'Grammar C1',
    description: 'Past Continuous, Perfect & Perfect Continuous'
  },
  {
    id: 'lesson_3_grammar_c1',
    label: 'Lesson 3',
    isStatic: true,
    group: 'Grammar C1',
    description: 'Will, Would, Should (Habits & Modals)'
  },
  {
    id: 'leccion_1_vocabulario_c1_s',
    label: 'Lección 1',
    isStatic: true,
    group: 'Vocabulario C1',
    description: 'Risas, Emociones y Reacciones'
  },
  {
    id: 'lesson_1_vocabulary_c1',
    label: 'Lesson 1',
    isStatic: true,
    group: 'Vocabulary C1',
    description: 'Laughing, Emotions & Reactions'
  },
  { id: "lesson_1", label: "Lesson 1", isStatic: true, group: "W2" },
  { id: "lesson_3", label: "Lesson 3", isStatic: true, group: "W2" },
  { id: "lesson_5", label: "Lesson 5", isStatic: true, group: "W2" },
  { id: "lesson_7", label: "Lesson 7", isStatic: true, group: "W2" },
  { id: "lesson_9", label: "Lesson 9", isStatic: true, group: "W2" },
  { id: "lesson_11", label: "Lesson 11", isStatic: true, group: "W2" },
  { id: "lesson_13", label: "Lesson 13", isStatic: true, group: "W2" },
  { id: "lesson_15", label: "Lesson 15", isStatic: true, group: "W2" },
  { id: "lesson_17", label: "Lesson 17", isStatic: true, group: "W2" },
  { id: "lesson_19", label: "Lesson 19", isStatic: true, group: "W2" },
  { id: "lesson_21", label: "Lesson 21", isStatic: true, group: "W2" },
  { id: "lesson_23", label: "Lesson 23", isStatic: true, group: "W2" },
  { id: "lesson_25", label: "Lesson 25", isStatic: true, group: "W2" },
  { id: "lesson_27", label: "Lesson 27", isStatic: true, group: "W2" },
  { id: "lesson_29", label: "Lesson 29", isStatic: true, group: "W2" },
  { id: "start_finish", label: "Lesson 31", isStatic: true, group: "W2" },
  { id: "lesson_33", label: "Lesson 33", isStatic: true, group: "W2" },
  { id: "write_think", label: "Lesson 35", isStatic: true, group: "W2" },
  { id: "to_be_intro", label: "Lesson 37", isStatic: true, group: "W2" },
  { id: "to_be_negative", label: "Lesson 39", isStatic: true, group: "W2" },
  {
    id: "to_be_interrogative",
    label: "Lesson 41",
    isStatic: true,
    group: "W2",
  },
  { id: "to_make_give", label: "Lesson 43", isStatic: true, group: "W2" },
  { id: "to_open_close", label: "Lesson 45", isStatic: true, group: "W2" },
  { id: "to_call_wait", label: "Lesson 47", isStatic: true, group: "W2" },
  { id: "to_wear_change", label: "Lesson 49", isStatic: true, group: "W2" },
  { id: "to_sell_pay", label: "Lesson 51", isStatic: true, group: "W2" },
  { id: "to_put_do", label: "Lesson 53", isStatic: true, group: "W2" },
  { id: "to_play_run", label: "Lesson 55", isStatic: true, group: "W2" },
  { id: "to_spend_travel", label: "Lesson 57", isStatic: true, group: "W2" },
  { id: "to_arrive_leave", label: "Lesson 59", isStatic: true, group: "W2" },

  { id: "to_move_put", label: "Lesson 61", isStatic: true, group: "W4" },
  { id: "share_rent", label: "Lesson 63", isStatic: true, group: "W4" },
  { id: "to_lose_find", label: "Lesson 65", isStatic: true, group: "W4" },
  { id: "to_be_past", label: "Lesson 67", isStatic: true, group: "W4" },
  {
    id: "to_be_past_questions",
    label: "Lesson 69",
    isStatic: true,
    group: "W4",
  },
  { id: "lesson_71", label: "Lesson 71", isStatic: true, group: "W4" },
  { id: "lesson_73", label: "Lesson 73", isStatic: true, group: "W4" },
  { id: "lesson_75", label: "Lesson 75", isStatic: true, group: "W4" },
  { id: "lesson_77", label: "Lesson 77", isStatic: true, group: "W4" },
  { id: "lesson_79", label: "Lesson 79", isStatic: true, group: "W4" },
  { id: "lesson_81", label: "Lesson 81", isStatic: true, group: "W4" },
  { id: "lesson_83", label: "Lesson 83", isStatic: true, group: "W4" },
  { id: "lesson_85", label: "Lesson 85", isStatic: true, group: "W4" },
  { id: "lesson_89", label: "Lesson 89", isStatic: true, group: "W4" },
  { id: "lesson_91", label: "Lesson 91", isStatic: true, group: "W4" },

  {
    id: "lesson_1_vocabulary_a1",
    label: "Lesson 1",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Everyday Objects",
  },
  {
    id: "lesson_2_vocabulary_a1",
    label: "Lesson 2",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Common Actions",
  },
  {
    id: "lesson_3_vocabulary_a1",
    label: "Lesson 3",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Family Members",
  },
  {
    id: "lesson_4_vocabulary_a1",
    label: "Lesson 4",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Basic Adjectives",
  },
  {
    id: "lesson_5_vocabulary_a1",
    label: "Lesson 5",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Daily Routine",
  },
  {
    id: "lesson_6_vocabulary_a1",
    label: "Lesson 6",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Days, Months & Seasons",
  },
  {
    id: "lesson_7_vocabulary_a1",
    label: "Lesson 7",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Meals & Food",
  },
  {
    id: "lesson_8_vocabulary_a1",
    label: "Lesson 8",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Countries, nationalities, and languages",
  },
  {
    id: "lesson_9_vocabulary_a1",
    label: "Lesson 9",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Store types and shopping",
  },
  {
    id: "lesson_10_vocabulary_a1",
    label: "Lesson 10",
    isStatic: true,
    group: "Vocabulary A1",
    description: "The 20 body parts",
  },
  {
    id: "lesson_11_vocabulary_a1",
    label: "Lesson 11",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Clothes and basic verbs",
  },
  {
    id: "lesson_12_vocabulary_a1",
    label: "Lesson 12",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Rooms and parts of the house",
  },
  {
    id: "lesson_13_vocabulary_a1",
    label: "Lesson 13",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Places in the city",
  },
  {
    id: "lesson_14_vocabulary_a1",
    label: "Lesson 14",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Restaurant vocabulary",
  },
  {
    id: "lesson_15_vocabulary_a1",
    label: "Lesson 15",
    isStatic: true,
    group: "Vocabulary A1",
    description: "Kitchen utensils",
  },
  {
    id: "lesson_1_grammar_a1",
    label: "Lesson 1",
    isStatic: true,
    group: "Grammar A1",
    description: "Verb 'To be' (Present)",
  },
  {
    id: "lesson_2_grammar_a1",
    label: "Lesson 2",
    isStatic: true,
    group: "Grammar A1",
    description: "Demonstratives (this, that, etc.)",
  },
  {
    id: "lesson_3_grammar_a1",
    label: "Lesson 3",
    isStatic: true,
    group: "Grammar A1",
    description: "Subject Pronouns",
  },
  {
    id: "lesson_4_grammar_a1",
    label: "Lesson 4",
    isStatic: true,
    group: "Grammar A1",
    description: "Plural Nouns",
  },
  {
    id: "lesson_5_grammar_a1",
    label: "Lesson 5",
    isStatic: true,
    group: "Grammar A1",
    description: "Adjectives (Order & Usage)",
  },
  {
    id: "lesson_6_grammar_a1",
    label: "Lesson 6",
    isStatic: true,
    group: "Grammar A1",
    description: "Present Simple",
  },
  {
    id: "lesson_7_grammar_a1",
    label: "Lesson 7",
    isStatic: true,
    group: "Grammar A1",
    description: "Questions (Wh- & Yes/No)",
  },
  {
    id: "lesson_1_grammar_a2",
    label: "Lesson 1",
    isStatic: true,
    group: "Grammar A2",
    description: "Questions (Wh- words, auxiliaries)",
  },
  {
    id: "lesson_2_grammar_a2",
    label: "Lesson 2",
    isStatic: true,
    group: "Grammar A2",
    description: "Subject vs Object Questions",
  },
  {
    id: "lesson_3_grammar_a2",
    label: "Lesson 3",
    isStatic: true,
    group: "Grammar A2",
    description: "Present Simple vs Continuous",
  },
  {
    id: "lesson_4_grammar_a2",
    label: "Lesson 4",
    isStatic: true,
    group: "Grammar A2",
    description: "Past Simple",
  },
  {
    id: "lesson_5_grammar_a2",
    label: "Lesson 5",
    isStatic: true,
    group: "Grammar A2",
    description: "Past Continuous",
  },
  {
    id: "lesson_1_grammar_b1",
    label: "Lesson 1",
    isStatic: true,
    group: "Grammar B1",
    description: "Present Simple vs Continuous",
  },
  { id: "leccion_1_w2_s", label: "Lección 1", isStatic: true, group: "W2-S" },
  { id: "leccion_3_w2_s", label: "Lección 3", isStatic: true, group: "W2-S" },
  { id: "leccion_5_w2_s", label: "Lección 5", isStatic: true, group: "W2-S" },
  { id: "leccion_7_w2_s", label: "Lección 7", isStatic: true, group: "W2-S" },
  { id: "leccion_9_w2_s", label: "Lección 9", isStatic: true, group: "W2-S" },
  { id: "leccion_11_w2_s", label: "Lección 11", isStatic: true, group: "W2-S" },
  { id: "leccion_13_w2_s", label: "Lección 13", isStatic: true, group: "W2-S" },
  { id: "leccion_15_w2_s", label: "Lección 15", isStatic: true, group: "W2-S" },
  { id: "leccion_17_w2_s", label: "Lección 17", isStatic: true, group: "W2-S" },
  { id: "leccion_19_w2_s", label: "Lección 19", isStatic: true, group: "W2-S" },
  { id: "leccion_21_w2_s", label: "Lección 21", isStatic: true, group: "W2-S" },
  { id: "leccion_23_w2_s", label: "Lección 23", isStatic: true, group: "W2-S" },
  { id: "leccion_25_w2_s", label: "Lección 25", isStatic: true, group: "W2-S" },
  { id: "leccion_27_w2_s", label: "Lección 27", isStatic: true, group: "W2-S" },
  { id: "leccion_29_w2_s", label: "Lección 29", isStatic: true, group: "W2-S" },
  { id: "leccion_31_w2_s", label: "Lección 31", isStatic: true, group: "W2-S" },
  { id: "leccion_33_w2_s", label: "Lección 33", isStatic: true, group: "W2-S" },
  { id: "leccion_35_w2_s", label: "Lección 35", isStatic: true, group: "W2-S" },
  { id: "leccion_37_w2_s", label: "Lección 37", isStatic: true, group: "W2-S" },
  { id: "leccion_39_w2_s", label: "Lección 39", isStatic: true, group: "W2-S" },
  { id: "leccion_41_w2_s", label: "Lección 41", isStatic: true, group: "W2-S" },
  { id: "leccion_43_w2_s", label: "Lección 43", isStatic: true, group: "W2-S" },
  { id: "leccion_45_w2_s", label: "Lección 45", isStatic: true, group: "W2-S" },
  { id: "leccion_47_w2_s", label: "Lección 47", isStatic: true, group: "W2-S" },
  { id: "leccion_49_w2_s", label: "Lección 49", isStatic: true, group: "W2-S" },
  {
    id: "leccion_1_vocabulario_a1_s",
    label: "Lección 1",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Objetos Cotidianos",
  },
  {
    id: "leccion_2_vocabulario_a1_s",
    label: "Lección 2",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Acciones Comunes",
  },
  {
    id: "leccion_3_vocabulario_a1_s",
    label: "Lección 3",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Miembros de la Familia",
  },
  {
    id: "leccion_4_vocabulario_a1_s",
    label: "Lección 4",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Adjetivos Básicos",
  },
  {
    id: "leccion_5_vocabulario_a1_s",
    label: "Lección 5",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Rutina Diaria",
  },
  {
    id: "leccion_6_vocabulario_a1_s",
    label: "Lección 6",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Días, Meses y Estaciones",
  },
  {
    id: "leccion_7_vocabulario_a1_s",
    label: "Lección 7",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Comidas y Alimentos",
  },
  {
    id: "leccion_8_vocabulario_a1_s",
    label: "Lección 8",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Países, nacionalidades e idiomas",
  },
  {
    id: "leccion_9_vocabulario_a1_s",
    label: "Lección 9",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Tipos de tienda y compras",
  },
  {
    id: "leccion_10_vocabulario_a1_s",
    label: "Lección 10",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Las 20 partes del cuerpo",
  },
  {
    id: "leccion_11_vocabulario_a1_s",
    label: "Lección 11",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Ropa y verbos básicos",
  },
  {
    id: "leccion_12_vocabulario_a1_s",
    label: "Lección 12",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Habitaciones y partes de la casa",
  },
  {
    id: "leccion_13_vocabulario_a1_s",
    label: "Lección 13",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Lugares de la ciudad",
  },
  {
    id: "leccion_14_vocabulario_a1_s",
    label: "Lección 14",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Vocabulario de restaurante",
  },
  {
    id: "leccion_15_vocabulario_a1_s",
    label: "Lección 15",
    isStatic: true,
    group: "Vocabulario A1",
    description: "Utensilios de cocina",
  },
  {
    id: "lesson_8_grammar_a1",
    label: "Lesson 8",
    isStatic: true,
    group: "Grammar A1",
    description: "Adverbs of Frequency",
  },
  {
    id: "lesson_9_grammar_a1",
    label: "Lesson 9",
    isStatic: true,
    group: "Grammar A1",
    description: "Subject & Object Pronouns",
  },
  {
    id: "lesson_10_grammar_a1",
    label: "Lesson 10",
    isStatic: true,
    group: "Grammar A1",
    description: "Possessive 's",
  },
  {
    id: "lesson_11_grammar_a1",
    label: "Lesson 11",
    isStatic: true,
    group: "Grammar A1",
    description: "Prepositions of Time",
  },
  {
    id: "lesson_12_grammar_a1",
    label: "Lesson 12",
    isStatic: true,
    group: "Grammar A1",
    description: "Prepositions of Place",
  },
  {
    id: "lesson_13_grammar_a1",
    label: "Lesson 13",
    isStatic: true,
    group: "Grammar A1",
    description: "Can / Cannot / Can't",
  },
  {
    id: "lesson_14_grammar_a1",
    label: "Lesson 14",
    isStatic: true,
    group: "Grammar A1",
    description: "Present Continuous (New Verbs)",
  },
  {
    id: "lesson_15_grammar_a1",
    label: "Lesson 15",
    isStatic: true,
    group: "Grammar A1",
    description: "Present Simple vs Continuous",
  },
  {
    id: "lesson_16_grammar_a1",
    label: "Lesson 16",
    isStatic: true,
    group: "Grammar A1",
    description: "Imperative / Commands",
  },
  {
    id: "lesson_17_grammar_a1",
    label: "Lesson 17",
    isStatic: true,
    group: "Grammar A1",
    description: "To be (Past)",
  },
  {
    id: "lesson_18_grammar_a1",
    label: "Lesson 18",
    isStatic: true,
    group: "Grammar A1",
    description: "Irregular Verbs",
  },
  {
    id: "lesson_19_grammar_a1",
    label: "Lesson 19",
    isStatic: true,
    group: "Grammar A1",
    description: "Form and Questions",
  },
  {
    id: "lesson_20_grammar_a1",
    label: "Lesson 20",
    isStatic: true,
    group: "Grammar A1",
    description: "The Four Rules",
  },
  {
    id: "lesson_21_grammar_a1",
    label: "Lesson 21",
    isStatic: true,
    group: "Grammar A1",
    description: "Would you like / I would like",
  },
  {
    id: "lesson_22_grammar_a1",
    label: "Lesson 22",
    isStatic: true,
    group: "Grammar A1",
    description: "Have you got / I have got",
  },
  {
    id: "lesson_23_grammar_a1",
    label: "Lesson 23",
    isStatic: true,
    group: "Grammar A1",
    description: "Some and any",
  },
  {
    id: "lesson_24_grammar_a1",
    label: "Lesson 24",
    isStatic: true,
    group: "Grammar A1",
    description: "There is / There are",
  },
  {
    id: "lesson_25_grammar_a1",
    label: "Lesson 25",
    isStatic: true,
    group: "Grammar A1",
    description: "There is / It is",
  },
  {
    id: "lesson_26_grammar_a1",
    label: "Lesson 26",
    isStatic: true,
    group: "Grammar A1",
    description: "Prepositions of place",
  },
  {
    id: "lesson_27_grammar_a1",
    label: "Lesson 27",
    isStatic: true,
    group: "Grammar A1",
    description: "Quantifiers",
  },
  {
    id: "lesson_28_grammar_a1",
    label: "Lesson 28",
    isStatic: true,
    group: "Grammar A1",
    description: "Comparatives",
  },
  {
    id: "lesson_29_grammar_a1",
    label: "Lesson 29",
    isStatic: true,
    group: "Grammar A1",
    description: "Superlatives",
  },
  {
    id: "lesson_30_grammar_a1",
    label: "Lesson 30",
    isStatic: true,
    group: "Grammar A1",
    description: "Future (will)",
  },
  {
    id: "lesson_31_grammar_a1",
    label: "Lesson 31",
    isStatic: true,
    group: "Grammar A1",
    description: "Future (going to)",
  },
  {
    id: "leccion_1_gramatica_a1_s",
    label: "Lección 1",
    isStatic: true,
    group: "Gramática A1",
    description: "Verbos 'Ser' y 'Estar'",
  },
  {
    id: "leccion_2_gramatica_a1_s",
    label: "Lección 2",
    isStatic: true,
    group: "Gramática A1",
    description: "Demostrativos (este, ese, etc.)",
  },
  {
    id: "leccion_3_gramatica_a1_s",
    label: "Lección 3",
    isStatic: true,
    group: "Gramática A1",
    description: "Pronombres Personales",
  },
  {
    id: "leccion_4_gramatica_a1_s",
    label: "Lección 4",
    isStatic: true,
    group: "Gramática A1",
    description: "Los Plurales",
  },
  {
    id: "leccion_5_gramatica_a1_s",
    label: "Lección 5",
    isStatic: true,
    group: "Gramática A1",
    description: "El uso de Adjetivos",
  },
  {
    id: "leccion_6_gramatica_a1_s",
    label: "Lección 6",
    isStatic: true,
    group: "Gramática A1",
    description: "Presente de Indicativo",
  },
  {
    id: "leccion_7_gramatica_a1_s",
    label: "Lección 7",
    isStatic: true,
    group: "Gramática A1",
    description: "Palabras interrogativas",
  },
  {
    id: "leccion_8_gramatica_a1_s",
    label: "Lección 8",
    isStatic: true,
    group: "Gramática A1",
    description: "Adverbios de Frecuencia",
  },
  {
    id: "leccion_9_gramatica_a1_s",
    label: "Lección 9",
    isStatic: true,
    group: "Gramática A1",
    description: "Pronombres Sujeto y Objeto",
  },
  {
    id: "leccion_10_gramatica_a1_s",
    label: "Lección 10",
    isStatic: true,
    group: "Gramática A1",
    description: "Posesivos con 'de'",
  },
  {
    id: "leccion_11_gramatica_a1_s",
    label: "Lección 11",
    isStatic: true,
    group: "Gramática A1",
    description: "Preposiciones de Tiempo",
  },
  {
    id: "leccion_12_gramatica_a1_s",
    label: "Lección 12",
    isStatic: true,
    group: "Gramática A1",
    description: "Preposiciones de Lugar",
  },
  {
    id: "leccion_13_gramatica_a1_s",
    label: "Lección 13",
    isStatic: true,
    group: "Gramática A1",
    description: "Saber / Poder",
  },
  {
    id: "leccion_14_gramatica_a1_s",
    label: "Lección 14",
    isStatic: true,
    group: "Gramática A1",
    description: "Presente Continuo (Verbos Nuevos)",
  },
  {
    id: "leccion_15_gramatica_a1_s",
    label: "Lección 15",
    isStatic: true,
    group: "Gramática A1",
    description: "Presente Simple vs Continuo",
  },
  {
    id: "leccion_16_gramatica_a1_s",
    label: "Lección 16",
    isStatic: true,
    group: "Gramática A1",
    description: "Forma y los cinco usos (Imperativo)",
  },
  {
    id: "leccion_17_gramatica_a1_s",
    label: "Lección 17",
    isStatic: true,
    group: "Gramática A1",
    description: "Verbo ser/estar (Pasado)",
  },
  {
    id: "leccion_18_gramatica_a1_s",
    label: "Lección 18",
    isStatic: true,
    group: "Gramática A1",
    description: "Verbos irregulares",
  },
  {
    id: "leccion_19_gramatica_a1_s",
    label: "Lección 19",
    isStatic: true,
    group: "Gramática A1",
    description: "Forma y preguntas",
  },
  {
    id: "leccion_20_gramatica_a1_s",
    label: "Lección 20",
    isStatic: true,
    group: "Gramática A1",
    description: "Irregularidades",
  },
  {
    id: "leccion_21_gramatica_a1_s",
    label: "Lección 21",
    isStatic: true,
    group: "Gramática A1",
    description: "El contraste",
  },
  {
    id: "leccion_22_gramatica_a1_s",
    label: "Lección 22",
    isStatic: true,
    group: "Gramática A1",
    description: "Tener",
  },
  {
    id: "leccion_23_gramatica_a1_s",
    label: "Lección 23",
    isStatic: true,
    group: "Gramática A1",
    description: "Cantidades indefinidas",
  },
  {
    id: "leccion_24_gramatica_a1_s",
    label: "Lección 24",
    isStatic: true,
    group: "Gramática A1",
    description: "Hay",
  },
  {
    id: "leccion_25_gramatica_a1_s",
    label: "Lección 25",
    isStatic: true,
    group: "Gramática A1",
    description: "Hay / Es",
  },
  {
    id: "leccion_26_gramatica_a1_s",
    label: "Lección 26",
    isStatic: true,
    group: "Gramática A1",
    description: "Preposiciones de lugar",
  },
  {
    id: "leccion_27_gramatica_a1_s",
    label: "Lección 27",
    isStatic: true,
    group: "Gramática A1",
    description: "Cuantificadores",
  },
  {
    id: "leccion_28_gramatica_a1_s",
    label: "Lección 28",
    isStatic: true,
    group: "Gramática A1",
    description: "Comparativos",
  },
  {
    id: "leccion_29_gramatica_a1_s",
    label: "Lección 29",
    isStatic: true,
    group: "Gramática A1",
    description: "Superlativos",
  },
  {
    id: "leccion_30_gramatica_a1_s",
    label: "Lección 30",
    isStatic: true,
    group: "Gramática A1",
    description: "Futuro (Simple)",
  },
  {
    id: "leccion_31_gramatica_a1_s",
    label: "Lección 31",
    isStatic: true,
    group: "Gramática A1",
    description: "Futuro (Ir a)",
  },
  {
    id: "leccion_1_gramatica_a2_s",
    label: "Lección 1",
    isStatic: true,
    group: "Gramática A2",
    description: "Preguntas (palabras interrogativas, auxiliares)",
  },
  {
    id: "leccion_2_gramatica_a2_s",
    label: "Lección 2",
    isStatic: true,
    group: "Gramática A2",
    description: "Preguntas de sujeto vs objeto",
  },
  {
    id: "leccion_3_gramatica_a2_s",
    label: "Lección 3",
    isStatic: true,
    group: "Gramática A2",
    description: "Presente Simple vs Continuo",
  },
  {
    id: "leccion_4_gramatica_a2_s",
    label: "Lección 4",
    isStatic: true,
    group: "Gramática A2",
    description: "Pasado Simple",
  },
  {
    id: "leccion_5_gramatica_a2_s",
    label: "Lección 5",
    isStatic: true,
    group: "Gramática A2",
    description: "Pasado Continuo",
  },
  {
    id: "leccion_1_gramatica_b1_s",
    label: "Lección 1",
    isStatic: true,
    group: "Gramática B1",
    description: "Presente Simple vs Continuo",
  },
  {
    id: "leccion_2_gramatica_b1_s",
    label: "Lección 2",
    isStatic: true,
    group: "Gramática B1",
    description: "Futuro: Ir a, Presente, Futuro",
  },
  {
    id: "lesson_2_grammar_b1",
    label: "Lesson 2",
    isStatic: true,
    group: "Grammar B1",
    description: "Future: Will, Be Going To, Present",
  },
  {
    id: "lesson_1_grammar_b1_plus",
    label: "Lesson 1",
    isStatic: true,
    group: "Grammar B1+",
    description: "Indirect Questions",
  },
  {
    id: "leccion_1_gramatica_b1_plus_s",
    label: "Lección 1",
    isStatic: true,
    group: "Gramática B1+",
    description: "Preguntas Indirectas",
  },
  {
    id: "lesson_2_grammar_b1_plus",
    label: "Lesson 2",
    isStatic: true,
    group: "Grammar B1+",
    description: "Indirect Questions+",
  },
  {
    id: "leccion_2_gramatica_b1_plus_s",
    label: "Lección 2",
    isStatic: true,
    group: "Gramática B1+",
    description: "Preguntas Indirectas+",
  },
  {
    id: "lesson_1_grammar_b2",
    label: "Lesson 1",
    isStatic: true,
    group: "Grammar B2",
    description: "Uses of Have",
  },
  {
    id: "leccion_1_gramatica_b2_s",
    label: "Lección 1",
    isStatic: true,
    group: "Gramática B2",
    description: "Usos de Haber/Tener",
  },
  {
    id: "lesson_2_grammar_b2",
    label: "Lesson 2",
    isStatic: true,
    group: "Grammar B2",
    description: "Connectors",
  },
  {
    id: "leccion_2_gramatica_b2_s",
    label: "Lección 2",
    isStatic: true,
    group: "Gramática B2",
    description: "Conectores",
  },
  {
    id: "dictionary_words_1",
    label: "Words 1",
    isStatic: true,
    group: "Dictionary",
    description: "Business English Vocabulary",
  },
  {
    id: "deberes_lesson_1_es",
    label: "Lección 1",
    isStatic: true,
    group: "Deberes",
    description: "Saudações, Verbo SER e Rotina",
  },
  {
    id: "deberes_lesson_2_es",
    label: "20 Verbos",
    isStatic: true,
    group: "Deberes",
    description: "Principais verbos em Espanhol",
  },

];
